#!/usr/bin/env python3
"""
Extract Common Core ELA standards to match existing standard.csv format.
Outputs in the exact same format as the existing Drupal system.
"""

import re
import csv
import json
import uuid
from pathlib import Path
from typing import Dict, List, Tuple


def generate_drupal_uuid() -> str:
    """Generate a UUID in the format used by Drupal."""
    return str(uuid.uuid4())


def extract_ela_standards_sample() -> List[Dict]:
    """
    Create sample ELA standards in the exact format of existing standard.csv.
    This demonstrates the correct format for any missing standards.
    """
    standards = []
    
    # Based on the existing format, here are the key field mappings:
    # field_standards_framework = 14782 (Common Core)
    # field_standards_taxonomy = 16468 (Anchor), 16469 (Cluster), 16470 (Grade-specific)
    # field_associated_grade_level = varies by grade
    
    # Grade level mappings (from examining existing data)
    grade_mappings = {
        'K': '14816',
        '1': '14817', 
        '2': '14818',
        '3': '14819',
        '4': '14820',
        '5': '14821',
        '6': '14822',
        '7': '14823',
        '8': '14824',
        '9-10': '14825',
        '11-12': '14826'
    }
    
    # Strand mappings (from examining existing data)
    strand_mappings = {
        'Reading Literature': '14827',
        'Reading Informational Text': '14828', 
        'Reading Foundational Skills': '14860',
        'Writing': '14829',
        'Speaking and Listening': '14830',
        'Language': '14831'
    }
    
    # Sample standards in the exact CSV format
    sample_standards = [
        {
            'nid': '',  # Auto-generated by Drupal
            'uuid': generate_drupal_uuid(),
            'title': 'CCSS.ELA-Literacy.RL.K.1',
            'body/format': '',
            'body/value': '<p>With prompting and support, ask and answer questions about key details in a text.</p>',
            'field_standards_framework': '14782',
            'field_standards_hierarchy': '',
            'field_standards_taxonomy': '16470',  # Grade-specific standard
            'field_anchor_standard_reference': '',
            'field_associated_grade_level': grade_mappings['K'],
            'field_org_level_1': strand_mappings['Reading Literature'],
            'field_org_level_2': '14840',  # Key Ideas and Details cluster
            'field_org_level_3': '',
            'field_standard_ref': 'CCSS.ELA-Literacy.RL.K.1',
            'field_substandard_ref': '',
            'field_marzano_tier_2': '',
            'field_marzano_tier_3_ela': '',
            'field_sep': '',
            'field_associated_assessment': '',
            'status': 'TRUE',
            'field_associated_unit': '',
            'field_c3_anchor_foundation': '',
            'field_c3_anchor_supportive': '',
            'field_c3_anchor_vital': '',
            'field_c3_cc_gl_foundational': '',
            'field_c3_gl_supportive': '',
            'field_c3_gl_vital': '',
            'field_ccc': '',
            'field_dci': '',
            'field_language_standard_ref': ''
        },
        {
            'nid': '',
            'uuid': generate_drupal_uuid(),
            'title': 'CCSS.ELA-Literacy.RL.1.1',
            'body/format': '',
            'body/value': '<p>Ask and answer questions about key details in a text.</p>',
            'field_standards_framework': '14782',
            'field_standards_hierarchy': '',
            'field_standards_taxonomy': '16470',
            'field_anchor_standard_reference': '',
            'field_associated_grade_level': grade_mappings['1'],
            'field_org_level_1': strand_mappings['Reading Literature'],
            'field_org_level_2': '14840',  # Key Ideas and Details
            'field_org_level_3': '',
            'field_standard_ref': 'CCSS.ELA-Literacy.RL.1.1',
            'field_substandard_ref': '',
            'field_marzano_tier_2': '',
            'field_marzano_tier_3_ela': '',
            'field_sep': '',
            'field_associated_assessment': '',
            'status': 'TRUE',
            'field_associated_unit': '',
            'field_c3_anchor_foundation': '',
            'field_c3_anchor_supportive': '',
            'field_c3_anchor_vital': '',
            'field_c3_cc_gl_foundational': '',
            'field_c3_gl_supportive': '',
            'field_c3_gl_vital': '',
            'field_ccc': '',
            'field_dci': '',
            'field_language_standard_ref': ''
        }
    ]
    
    return sample_standards


def write_standards_csv(standards: List[Dict], output_file: Path):
    """Write standards in the exact CSV format of existing standard.csv."""
    
    # Exact fieldnames from existing CSV
    fieldnames = [
        'nid', 'uuid', 'title', 'body/format', 'body/value', 'field_standards_framework',
        'field_standards_hierarchy', 'field_standards_taxonomy', 'field_anchor_standard_reference',
        'field_associated_grade_level', 'field_org_level_1', 'field_org_level_2', 'field_org_level_3',
        'field_standard_ref', 'field_substandard_ref', 'field_marzano_tier_2', 'field_marzano_tier_3_ela',
        'field_sep', 'field_associated_assessment', 'status', 'field_associated_unit',
        'field_c3_anchor_foundation', 'field_c3_anchor_supportive', 'field_c3_anchor_vital',
        'field_c3_cc_gl_foundational', 'field_c3_gl_supportive', 'field_c3_gl_vital',
        'field_ccc', 'field_dci', 'field_language_standard_ref'
    ]
    
    with open(output_file, 'w', newline='', encoding='utf-8') as f:
        # Write BOM for UTF-8 (matching existing file)
        f.write('\ufeff')
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(standards)


def create_mapping_guide(output_dir: Path):
    """Create a guide showing the field mappings discovered from existing data."""
    guide = {
        "format_notes": "This script creates CSV files that match the exact format of the existing standard.csv file",
        "key_field_mappings": {
            "field_standards_framework": "14782 (Common Core)",
            "field_standards_taxonomy": {
                "16468": "Anchor Standards (CCRA)",
                "16469": "Cluster/Domain level", 
                "16470": "Grade-specific standards"
            },
            "grade_level_mappings": {
                "K": "14816",
                "1": "14817",
                "2": "14818", 
                "3": "14819",
                "4": "14820",
                "5": "14821",
                "6": "14822",
                "7": "14823",
                "8": "14824",
                "9-10": "14825",
                "11-12": "14826"
            },
            "strand_mappings": {
                "Reading Literature": "14827",
                "Reading Informational Text": "14828",
                "Reading Foundational Skills": "14860", 
                "Writing": "14829",
                "Speaking and Listening": "14830",
                "Language": "14831"
            }
        },
        "status": "1,044 Common Core ELA standards already exist in the system. This script provides the correct format for any additional standards needed."
    }
    
    with open(output_dir / 'ela_format_mapping_guide.json', 'w') as f:
        json.dump(guide, f, indent=2)


def main():
    """Main execution function."""
    output_dir = Path("data/output/drupal_prep/01_ela_common_core")
    output_dir.mkdir(parents=True, exist_ok=True)
    
    print("Creating sample ELA standards in correct format...")
    
    # Get sample standards
    standards = extract_ela_standards_sample()
    
    # Write in exact CSV format
    output_file = output_dir / 'ela_cc_standards_drupal_format.csv'
    write_standards_csv(standards, output_file)
    
    # Create mapping guide
    create_mapping_guide(output_dir)
    
    print(f"Sample standards created in correct format:")
    print(f"  - {output_file}")
    print(f"  - {output_dir / 'ela_format_mapping_guide.json'}")
    print(f"\nNote: The existing system already contains 1,044 Common Core ELA standards.")
    print(f"This script demonstrates the correct format for any additional standards needed.")


if __name__ == "__main__":
    main()